### PR TITLE
Fix typo error

### PR DESCRIPTION
**Pull request by fernandomema**
number_forma to number_format

### CODE REVIEW

**Comment by MinePlay85** [comment]
Hello,
After this the order page work ?

**Comment by fernandomema** [comment]
yes, the page now does not return the error that the function does not exist.

**Comment by MinePlay85** [comment]
Hello,
I will test it, in the demo website.
if it's work i will merge the pull request !

**Comment by MinePlay85** [comment]
There work.
You can look here: https://demo.pterobilling.org/order/1
Thank you for your help.
Bye !

**Pull request merged**
